// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHeSUs3cULciWhe4mMhWU1sFCLNt4JFoo',
    appId: '1:1047742717284:web:f0485aa5910fa0e2b9ae71',
    messagingSenderId: '1047742717284',
    projectId: 'easywash-ew',
    authDomain: 'easywash-ew.firebaseapp.com',
    storageBucket: 'easywash-ew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_XOBUhzbWtPhVsBEfCKjaQrM3M7eOtPo',
    appId: '1:1047742717284:android:06a8d6454f52e6cab9ae71',
    messagingSenderId: '1047742717284',
    projectId: 'easywash-ew',
    storageBucket: 'easywash-ew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHXEEDVBTguxXAiOe2ssRgQirN9Oz7pA',
    appId: '1:1047742717284:ios:45b1023d4f0e8aacb9ae71',
    messagingSenderId: '1047742717284',
    projectId: 'easywash-ew',
    storageBucket: 'easywash-ew.appspot.com',
    iosClientId: '1047742717284-6o02p1h1cca9see27qg9bih6d3vga5h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.easywash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqHXEEDVBTguxXAiOe2ssRgQirN9Oz7pA',
    appId: '1:1047742717284:ios:45b1023d4f0e8aacb9ae71',
    messagingSenderId: '1047742717284',
    projectId: 'easywash-ew',
    storageBucket: 'easywash-ew.appspot.com',
    iosClientId: '1047742717284-6o02p1h1cca9see27qg9bih6d3vga5h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.easywash',
  );
}
